export enum Route {
  LOGIN = "/login",
  SIGNUP = "/signup",
  FORGOT_PASSWORD = "/forgot-password",
  RESET_PASSWORD = "/reset-password",
  VERIFY_EMAIL = "/verify-email",
  CHAT = "/chat",
  CONVERSATIONS = "/chat/conversations",
  PROFILE = "/chat/profile",
  SETTINGS = "/chat/settings",
  REQUESTS = "/chat/requests",
  TERMS = "/terms",
  PRIVACY = "/privacy",
  PRICING = "/pricing",
  FAQ = "/faq",
}
